services:
  api:
    build: .
    container_name: papersoul-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://${ROOT_USERNAME}:${ROOT_PASSWORD}@mongodb:27017/?authSource=admin
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      SECRET_KEY: ${SECRET_KEY}
      MAX_FILE_SIZE_BYTES: ${MAX_FILE_SIZE_BYTES}
      MIN_TEXT_LENGTH: ${MIN_TEXT_LENGTH}
      MIN_DPI: ${MIN_DPI}
    networks:
      - mired

networks:
  mired:
    external: true